# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.3
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: List all changed files
        run: |
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              echo "$file was changed"
            done

      - run: npm install -g ebnf2railroad
      - run: ebnf2railroad docs/grammar.ebnf -o docs/index.html
      - run: |
            git config --global user.name 'Github Actions'
            git config --global user.email 'github@actions.bot'
            git add -f docs/index.html
            git commit -am "update grammar.html"
            git push
